name: tekartik_mustache_repo
version: 0.1.1
author: Alexandre Roux Tekartik <alex@tekartik.com>
description: Tekartik mustache repo
homepage: https://github.com/tekartik/mustache.dart
environment:
  sdk: '>=2.0.0-dev.63 <3.0.0'
dev_dependencies:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.6.5'

# dependency_overrides:
#  tekartik_build_utils:
#    path: ../build_utils.dart