name: tekartik_mustache_repo
version: 0.2.1
author: Alexandre Roux Tekartik <alex@tekartik.com>
description: Tekartik mustache repo
homepage: https://github.com/tekartik/mustache.dart
environment:
  sdk: '>=2.1.0-dev <3.0.0'
dev_dependencies:
  chrome_travis:
    git:
      url: git://github.com/tekartik/chrome_travis.dart
      ref: dart2
  tekartik_build_utils:
    git:
      url: git://github.com/tekartik/build_utils.dart
      ref: dart2
    version: '>=0.6.5'
  process_run: '>=0.10.2'

  # test dependencies without version
  tekartik_mustache:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache
      ref: dart2
  tekartik_mustache_fs:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache_fs
      ref: dart2
  tekartik_mustache_cli:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache_cli
      ref: dart2
