name: tekartik_mustache_fs
version: 0.1.0
description: Mustache and fs together
environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  fs_shim: '>=0.8.1'
  tekartik_mustache:
    git:
      url: git@gitlab.com:tekartik/mustache.dart
      path: mustache
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
  yaml: any

dev_dependencies:
  test: any

dependency_overrides:
  tekartik_mustache:
    path: ../mustache
  tekartik_firebase_sembast:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sembast