name: tekartik_mustache_fs
version: 0.2.0
description: Mustache and fs together
environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  fs_shim: '>=0.8.2'
  idb_shim: '>=1.5.0'
  tekartik_mustache:
    git:
      url: git@gitlab.com:tekartik/mustache.dart
      path: mustache
  tekartik_firebase:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase
  yaml: any

dev_dependencies:
  test: any

dependency_overrides:
  fs_shim:
#    path: ../../../../github.com/tekartik/fs_shim.dart/fs
    git:
      url: git://github.com/tekartik/fs_shim.dart
      path: fs
  tekartik_mustache:
    path: ../mustache
  tekartik_firebase_sembast:
    git:
      url: git://github.com/tekartik/firebase.dart
      path: firebase_sembast