name: tekartik_mustache_fs
version: 0.2.1
description: Mustache and fs together
publish_to: none
environment:
  sdk: ^3.9.0

dependencies:
  fs_shim: ">=2.3.3+1"
  tekartik_mustache:
    git:
      url: https://github.com/tekartik/mustache.dart
      path: mustache
      ref: dart3a
    version: '>=0.2.1'
  tekartik_firebase_storage:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart3a
    version: '>=0.3.7'
  yaml: ">=3.1.2"
  path: ">=1.9.0"
dev_dependencies:
  test: ">=1.24.0"
  tekartik_firebase_storage_fs:
    git:
      url: https://github.com/tekartik/firebase_storage.dart
      path: storage_fs
      ref: dart3a
    version: '>=0.3.7'
  process_run: ">=1.2.1+1"

dependency_overrides:
  #  fs_shim:
  #    path: ../../../../github.com/tekartik/fs_shim.dart/fs
  #    git:
  #      url: https://github.com/tekartik/fs_shim.dart
  #      path: fs
  tekartik_mustache:
    path: ../mustache
#  tekartik_firebase_sembast:
#    git:
#      url: https://github.com/tekartik/firebase.dart
#      path: firebase_sembast
