name: tekartik_mustache_fs
version: 0.2.1
description: Mustache and fs together
environment:
  sdk: '>=2.1.0-dev <3.0.0'

dependencies:
  fs_shim: '>=0.11.0+1'
  tekartik_mustache:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache
      ref: dart2
    version: '>=0.2.1'
  tekartik_firebase_storage:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage
      ref: dart2
    version: '>=0.3.7'
  yaml: any

dev_dependencies:
  test: any
  tekartik_firebase_storage_fs:
    git:
      url: git://github.com/tekartik/firebase_storage.dart
      path: storage_fs
      ref: dart2
    version: '>=0.3.7'
  process_run: '>=0.10.2'

dependency_overrides:
#  fs_shim:
#    path: ../../../../github.com/tekartik/fs_shim.dart/fs
#    git:
#      url: git://github.com/tekartik/fs_shim.dart
#      path: fs
  tekartik_mustache:
    path: ../mustache
#  tekartik_firebase_sembast:
#    git:
#      url: git://github.com/tekartik/firebase.dart
#      path: firebase_sembast