name: tekartik_mustache_cli
version: 0.1.0
description: Mustache client
environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  fs_shim: '>=0.8.1'
  tekartik_mustache:
    git:
      url: git@gitlab.com:tekartik/mustache.dart
      path: mustache
  tekartik_mustache_fs:
    git:
      url: git@gitlab.com:tekartik/mustache.dart
      path: mustache_fs

dev_dependencies:
  test: any
  yaml: any

dependency_overrides:
  tekartik_mustache:
    path: ../mustache
  tekartik_mustache_fs:
    path: ../mustache_fs