name: tekartik_mustache_cli
version: 0.2.2
description: Mustache client
environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  fs_shim: '>=0.8.1'
  tekartik_mustache:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache
      ref: dart2
    version: '>=0.2.1'
  tekartik_mustache_fs:
    git:
      url: git://github.com/tekartik/mustache.dart
      path: mustache_fs
      ref: dart2
    version: '>=0.2.1'
  args: any
  pub_semver: any

dev_dependencies:
  test: any
  yaml: any
  process_run: '>=0.10.9-dev.1'

dependency_overrides:
  tekartik_mustache:
    path: ../mustache
  tekartik_mustache_fs:
    path: ../mustache_fs

