name: mustache_repo_support
description: Mustache repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: ^3.5.0

dev_dependencies:
  dev_build: '>=0.13.0'
  path:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart3a
      path: packages/lints
    version: '>=0.1.0'

