name: mustache_repo_support
description: Mustache repo (tools)
version: 0.2.0
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  dev_test: '>=0.13.0'
  pedantic:
  path:
  tekartik_lints:
    git:
      url: https://github.com/tekartik/common.dart
      ref: dart2_3
      path: packages/lints
    version: '>=0.1.0'

