name: tekartik_mustache
version: 0.1.0
description: Mustache dart implementation
environment:
  sdk: '>=1.24.3 <2.0.0'

dependencies:
  dart2_constant: any
  tekartik_common_utils:
    git: git://github.com/tekartik/common_utils.dart

dev_dependencies:
  test: any
  yaml: any
