name: tekartik_mustache
version: 0.3.1
description: Mustache dart implementation
publish_to: none
environment:
  sdk: ^3.7.0

dependencies:
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart3a
    version: '>=0.10.7'
  collection: ">=1.18.0"
dev_dependencies:
  test: ">=1.24.0"
  yaml: ">=3.1.2"
  process_run: ">=1.2.1+1"
  path: ">=1.9.0"
