name: tekartik_mustache
version: 0.3.0
description: Mustache dart implementation
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dart2_constant: any
  tekartik_common_utils:
    git:
      url: https://github.com/tekartik/common_utils.dart
      ref: dart2_3
    version: '>=0.10.7'

dev_dependencies:
  test: any
  yaml: any
  process_run: '>=0.10.9-dev.1'