name: tekartik_mustache
version: 0.3.0
description: Mustache dart implementation
environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  dart2_constant: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2
    version: '>=0.10.7'

dev_dependencies:
  test: any
  yaml: any
  process_run: '>=0.10.2'