name: tekartik_mustache
version: 0.1.0
description: Mustache dart implementation
environment:
  sdk: '>=2.0.0-dev.61 <2.0.0'

dependencies:
  dart2_constant: any
  tekartik_common_utils:
    git:
      url: git://github.com/tekartik/common_utils.dart
      ref: dart2

dev_dependencies:
  test: any
  yaml: any
